discord:
  api:
    clientId: "#{DISCORD_API_CLIENT_ID}"
    clientSecret: "#{DISCORD_API_CLIENT_SECRET}"
  bot:
    token: "#{DISCORD_BOT_TOKEN}"
    prefix: "#{DISCORD_BOT_PREFIX}"
    version: "#{Octopus.Release.Number}"
    db-channel: "#{DISCORD_DB_CHANNEL}"
    audit-channel: "#{DISCORD_AUDIT_CHANNEL}"
  polr:
    base-url: "#{POLR_BASE_URL}"
    api-key: "#{POLR_API_KEY}"
logging.level:
  sx.blah.discord: debug
  nu.peg.discord: debug