discord:
  api:
    clientId: "#{DISCORD_API_CLIENT_ID}"
    clientSecret: "#{DISCORD_API_CLIENT_SECRET}"
  bot:
    token: "#{DISCORD_BOT_TOKEN}"
    prefix: "#{DISCORD_BOT_PREFIX}"
    version: "#{Octopus.Release.Number}"